- name: my 1st playbook
  hosts: localhost
  vars:
    animal: "tiger"   #
  vars_files:
    - ./var/txt
  tasks:
    - name: print animal 
      debug:
        msg: "{{animal}}"
    - name: print animal2
      debug:
        msg: "{{animal}}"
    - name: print animal3
      debug:
        msg: "{{animal}}"
      vars:
        animal: "lion"



