apiVersion: v1
kind: Service
metadata: 
  name: my-svc-node
  labels:
    app: my-svc-node
    env: devops
  spec: 
    type: NodePort
    selector:
      app: my-app2
    ports:
      - name: http
        protocol: TCP
        targetport: 80
